sudo: false
language: python

cache:
  directories:
    - "~/.platformio"

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TARGET=Lint2.7
      install: pip install -e . && pip install flake8==3.6.0 pylint==1.9.4 pillow
      script:
        - flake8 esphome
        - pylint esphome
    - python: "3.5.3"
      env: TARGET=Lint3.5
      install: pip install -U https://github.com/platformio/platformio-core/archive/develop.zip && pip install -e . && pip install flake8==3.6.0 pylint==2.3.0 pillow
      script:
        - flake8 esphome
        - pylint esphome
    - python: "2.7"
      env: TARGET=Test2.7
      install: pip install -e . && pip install flake8==3.6.0 pylint==1.9.4 pillow
      script:
        - esphome tests/test1.yaml compile
        - esphome tests/test2.yaml compile
        - esphome tests/test3.yaml compile
    #- python: "3.5.3"
    #  env: TARGET=Test3.5
    #  install: pip install -U https://github.com/platformio/platformio-core/archive/develop.zip && pip install -e . && pip install flake8==3.6.0 pylint==2.3.0 pillow
    #  script:
    #    - esphome tests/test1.yaml compile
    #    - esphome tests/test2.yaml compile
